$ANSIBLE_VAULT;1.1;AES256
61333364383736646462353264373435636237303638303466303838396331653866353065336331
6139393831383964333065363039366163306532373665350a393331653737336461666565343464
38626538313264633335333733373365633563363261336630343564346165353433336433353563
6135363261383766310a623766313163383565636165376630656566376138353764353430373038
66633636646331653736383930323539653665303363653362383038396535653332316666616362
3066646464636563663338616362333561343631653738616336
